FROM  italiangrid/pkg.base:centos5

ENV BUILD_NAME argus-pep-server
ENV BUILD_REPO git://github.com/argus-authz/argus-pep-server
ENV BUILD_TAG 1_7
ENV PKG_REPO git://github.com/argus-authz/pkg.argus.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE argus-pep-server/rpm/pep-server/argus-pep-server.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
