FROM  italiangrid/pkg.base:centos6

ENV BUILD_NAME argus-pep-common
ENV BUILD_REPO git://github.com/argus-authz/argus-pep-common
ENV BUILD_TAG 2_3
ENV PKG_REPO git://github.com/argus-authz/pkg.argus.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE argus-pep-common/rpm/pep-common/argus-pep-common.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
