FROM  italiangrid/pkg.base:centos5

RUN yum -y install curl-devel

ENV BUILD_NAME argus-pep-api-c
ENV BUILD_REPO git://github.com/argus-authz/argus-pep-api-c
ENV BUILD_TAG 2_3
ENV PKG_REPO git://github.com/argus-authz/pkg.argus.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE argus-pep-api-c/rpm/pep-api-c/argus-pep-api-c.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
