FROM  italiangrid/pkg.base:centos5

RUN yum -y install argus-pep-api-c-devel

ENV BUILD_NAME argus-pep-cli
ENV BUILD_REPO git://github.com/argus-authz/argus-pep-cli
ENV BUILD_TAG 2_2
ENV PKG_REPO git://github.com/argus-authz/pkg.argus.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE argus-pep-cli/rpm/pep-cli/argus-pep-cli.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
