FROM  italiangrid/pkg.base:centos7

ENV BUILD_NAME argus-pdp
ENV BUILD_REPO git://github.com/argus-authz/argus-pdp
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/argus-authz/pkg.argus.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE argus-pdp/rpm/pdp/argus-pdp.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
